services:
  - type: web
    name: be3-77325-backend-app
    env: node
    plan: free
    buildCommand: npm ci --omit:dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: MiClaveUltraMegaSecreta
      - key: LOG_LEVEL
        value: info
      - key: USERS_COUNT
        value: 30
    autoDeploy: true
    branch: clase_08_a
