services:
  - type: web
    name: be3-77325-backend
    env: node
    plan: free
    branch: clase_08
    rootDir: new_proyect
    buildCommand: npm ci && npm run build && npm prune --omit=dev
    startCommand: npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
    autoDeployTrigger: commit
